name = "revforgehq-site"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "./dist/worker/index.js"

[assets]
directory = "."
binding = "ASSETS"

[ai]
binding = "AI"

[triggers]
crons = ["0 3 * * *", "0 6 * * *"]
